import type { ExportedSurface, TypeNode } from '../../scanner/types';
import { renderSurface } from '../renderSurface';

const Bool: TypeNode = { kind: 'primitive', name: 'Bool', typeof: 'boolean' };
const Int: TypeNode = { kind: 'primitive', name: 'Int', typeof: 'number' };
const Double: TypeNode = { kind: 'primitive', name: 'Double', typeof: 'number' };
const Str: TypeNode = { kind: 'primitive', name: 'String', typeof: 'string' };

const FILE = '/repo/packages/expo-video/ios/Demo.swift';

/** The surface `scan-exports` reports for the sample in the scanner's own docs. */
const sampleSurface: ExportedSurface = {
  records: [
    {
      name: 'Options',
      file: FILE,
      properties: [
        { name: 'quality', type: Double, optional: false, required: false },
        { name: 'name', type: { kind: 'optional', wrapped: Str }, optional: true, required: false },
        { name: 'tags', type: { kind: 'array', element: Str }, optional: false, required: true },
      ],
    },
  ],
  sharedObjects: [
    {
      name: 'VideoPlayer',
      jsName: 'Player',
      file: FILE,
      constructorParameters: [
        { label: 'url', name: 'url', type: Str, optional: false },
        {
          label: 'options',
          name: 'options',
          type: { kind: 'optional', wrapped: { kind: 'ref', name: 'Options' } },
          optional: true,
        },
      ],
      properties: [
        { name: 'isPlaying', jsName: 'isPlaying', type: Bool, readonly: false, static: false },
        { name: 'duration', jsName: 'duration', type: Double, readonly: true, static: false },
      ],
      functions: [
        {
          name: 'seekTo',
          jsName: 'seek',
          parameters: [{ label: '_', name: 'time', type: Double, optional: false }],
          async: false,
          throws: true,
          static: false,
        },
        {
          name: 'load',
          jsName: 'load',
          parameters: [
            { label: 'from', name: 'url', type: Str, optional: false },
            {
              label: 'onProgress',
              name: 'onProgress',
              type: { kind: 'function', parameters: [Double], async: false, throws: false },
              optional: false,
            },
          ],
          returns: { kind: 'dictionary', key: Str, value: Int },
          async: true,
          throws: true,
          static: false,
        },
        {
          name: 'create',
          jsName: 'create',
          parameters: [],
          returns: { kind: 'ref', name: 'VideoPlayer' },
          async: false,
          throws: false,
          static: true,
        },
      ],
    },
  ],
  modules: [
    {
      name: 'MyModule',
      jsName: 'MyModule',
      file: FILE,
      functions: [
        {
          name: 'greet',
          jsName: 'greet',
          parameters: [
            { label: '_', name: 'name', type: Str, optional: false },
            { label: 'loudly', name: 'loudly', type: Bool, optional: true },
          ],
          returns: Str,
          async: false,
          throws: false,
          static: false,
        },
      ],
      properties: [
        { name: 'version', jsName: 'version', type: Str, readonly: true, static: false },
      ],
    },
  ],
};

const emptySurface: ExportedSurface = { modules: [], sharedObjects: [], records: [] };

describe(renderSurface, () => {
  it('renders records, shared objects, and modules as a NativeModule subclass in dependency order', () => {
    const result = renderSurface(sampleSurface);
    expect(result.warnings).toEqual([]);
    expect(result.source).toBe(
      `// @generated by @expo/modules-cli. Do not edit by hand.
// Regenerate with \`expo-modules generate-types\`.

import type { NativeModule } from 'expo-modules-core';

export type Options = {
  quality?: number;
  name?: string | null;
  tags: string[];
};

export declare class Player {
  constructor(url: string, options?: Options | null);
  isPlaying: boolean;
  readonly duration: number;
  seek(time: number): void;
  load(url: string, onProgress: (arg0: number) => void): Promise<Record<string, number>>;
  static create(): Player;
}

export declare class MyModule extends NativeModule {
  readonly version: string;
  greet(name: string, loudly?: boolean): string;
}
`
    );
  });

  it('returns null source for an empty surface', () => {
    expect(renderSurface(emptySurface).source).toBeNull();
  });

  it('keeps an omittable parameter required when a required one follows it', () => {
    const result = renderSurface({
      ...emptySurface,
      modules: [
        {
          name: 'M',
          jsName: 'M',
          file: FILE,
          properties: [],
          functions: [
            {
              name: 'f',
              jsName: 'f',
              parameters: [
                { label: 'a', name: 'a', type: Int, optional: true },
                { label: 'b', name: 'b', type: Int, optional: false },
              ],
              async: false,
              throws: false,
              static: false,
            },
          ],
        },
      ],
    });
    expect(result.source).toContain('f(a: number | undefined, b: number): void;');
  });

  it('does not double-wrap a promise returned from an async function', () => {
    const result = renderSurface({
      ...emptySurface,
      modules: [
        {
          name: 'M',
          jsName: 'M',
          file: FILE,
          properties: [],
          functions: [
            {
              name: 'f',
              jsName: 'f',
              parameters: [],
              returns: { kind: 'promise', value: Int },
              async: true,
              throws: false,
              static: false,
            },
            {
              name: 'g',
              jsName: 'g',
              parameters: [],
              async: true,
              throws: false,
              static: false,
            },
          ],
        },
      ],
    });
    expect(result.source).toContain('f(): Promise<number>;');
    expect(result.source).toContain('g(): Promise<void>;');
  });

  it('maps well-known expo-modules-core types and imports the ones core exports', () => {
    const result = renderSurface({
      ...emptySurface,
      modules: [
        {
          name: 'M',
          jsName: 'M',
          file: FILE,
          properties: [],
          functions: [
            {
              name: 'fill',
              jsName: 'fill',
              parameters: [
                {
                  label: 'array',
                  name: 'array',
                  type: { kind: 'ref', name: 'TypedArray' },
                  optional: false,
                },
                {
                  label: 'buffer',
                  name: 'buffer',
                  type: { kind: 'ref', name: 'ArrayBuffer' },
                  optional: false,
                },
              ],
              returns: { kind: 'ref', name: 'TypedArray' },
              async: false,
              throws: false,
              static: false,
            },
          ],
        },
      ],
    });
    expect(result.warnings).toEqual([]);
    expect(result.source).toBe(
      `// @generated by @expo/modules-cli. Do not edit by hand.
// Regenerate with \`expo-modules generate-types\`.

import type { NativeModule, TypedArray } from 'expo-modules-core';

export declare class M extends NativeModule {
  fill(array: TypedArray, buffer: ArrayBuffer): TypedArray;
}
`
    );
  });

  it('lets a scanned type shadow a well-known core type of the same name', () => {
    const result = renderSurface({
      ...emptySurface,
      records: [{ name: 'TypedArray', file: FILE, properties: [] }],
      modules: [
        {
          name: 'M',
          jsName: 'M',
          file: FILE,
          properties: [
            {
              name: 'a',
              jsName: 'a',
              type: { kind: 'ref', name: 'TypedArray' },
              readonly: true,
              static: false,
            },
          ],
          functions: [],
        },
      ],
    });
    expect(result.source).toContain("import type { NativeModule } from 'expo-modules-core';");
    expect(result.source).not.toContain('TypedArray }');
    expect(result.source).toContain('readonly a: TypedArray;');
  });

  it('imports a type owned by another generated file', () => {
    const result = renderSurface(
      {
        ...emptySurface,
        modules: [
          {
            name: 'B',
            jsName: 'B',
            file: FILE,
            properties: [
              {
                name: 'player',
                jsName: 'player',
                type: { kind: 'ref', name: 'VideoPlayer' },
                readonly: true,
                static: false,
              },
            ],
            functions: [],
          },
        ],
      },
      { externalTypes: { VideoPlayer: { name: 'Player', from: './A.types' } } }
    );
    expect(result.warnings).toEqual([]);
    expect(result.source).toContain("import type { NativeModule } from 'expo-modules-core';\n");
    expect(result.source).toContain("import type { Player } from './A.types';\n");
    expect(result.source).toContain('readonly player: Player;');
  });

  it('quotes member names that are not identifiers and renames reserved-word parameters', () => {
    const result = renderSurface({
      ...emptySurface,
      modules: [
        {
          name: 'M',
          jsName: 'M',
          file: FILE,
          properties: [
            { name: 'someName', jsName: 'some-name', type: Int, readonly: true, static: false },
          ],
          functions: [
            {
              name: 'doIt',
              jsName: 'do-it',
              parameters: [{ label: 'default', name: 'default', type: Int, optional: false }],
              async: false,
              throws: false,
              static: false,
            },
          ],
        },
      ],
    });
    expect(result.warnings).toEqual([]);
    expect(result.source).toContain("readonly 'some-name': number;");
    expect(result.source).toContain("'do-it'(default_: number): void;");
  });

  it('skips a shared object or record whose name is not an identifier and warns', () => {
    const result = renderSurface({
      ...emptySurface,
      records: [{ name: 'Bad-Name', file: FILE, properties: [] }],
      sharedObjects: [
        { name: 'Player', jsName: 'my player', file: FILE, functions: [], properties: [] },
      ],
    });
    expect(result.source).toBeNull();
    expect(result.warnings).toEqual([
      {
        file: FILE,
        location: 'Bad-Name',
        message: "'Bad-Name' is not a valid TypeScript identifier, so its declaration was skipped",
      },
      {
        file: FILE,
        location: 'Player',
        message: "'my player' is not a valid TypeScript identifier, so its declaration was skipped",
      },
    ]);
  });

  it('reports warnings with the Swift location of the offending member', () => {
    const result = renderSurface({
      ...emptySurface,
      sharedObjects: [
        {
          name: 'VideoPlayer',
          jsName: 'Player',
          file: FILE,
          constructorParameters: null,
          properties: [
            {
              name: 'status',
              jsName: 'status',
              type: { kind: 'ref', name: 'PlaybackStatus' },
              readonly: true,
              static: false,
            },
            { name: 'untyped', jsName: 'untyped', readonly: true, static: false },
          ],
          functions: [
            {
              name: 'move',
              jsName: 'move',
              parameters: [
                {
                  label: 'to',
                  name: 'point',
                  type: { kind: 'unknown', text: '(Int, Int)' },
                  optional: false,
                },
              ],
              async: false,
              throws: false,
              static: false,
            },
          ],
        },
      ],
    });
    expect(result.source).toContain('readonly status: unknown;');
    expect(result.source).toContain('readonly untyped: unknown;');
    expect(result.source).toContain('move(point: unknown): void;');
    expect(result.warnings).toEqual([
      {
        file: FILE,
        location: 'VideoPlayer.status',
        message: "unresolved type 'PlaybackStatus' rendered as unknown",
      },
      {
        file: FILE,
        location: 'VideoPlayer.untyped',
        message: 'type could not be determined from the declaration, rendered as unknown',
      },
      {
        file: FILE,
        location: 'VideoPlayer.move(point)',
        message: "unmodeled Swift type '(Int, Int)' rendered as unknown",
      },
    ]);
  });
});
