import type {
  ExportedFunction,
  ExportedModule,
  ExportedParameter,
  ExportedProperty,
  ExportedRecord,
  ExportedSharedObject,
  ExportedSurface,
} from '../scanner/types';
import { isIdentifier, memberName, parameterName } from './identifiers';
import { renderReturnType, renderType, type RenderContext } from './renderType';

export type RenderWarning = {
  /** Absolute path of the Swift file declaring the member. */
  file: string;
  /** The member in Swift names: `Type.member`, or `Type.function(parameter)` for a parameter. */
  location: string;
  message: string;
};

/** Swift type name -> the TS name to use and the module specifier to import it from. */
export type ExternalTypes = Record<string, { name: string; from: string }>;

export type RenderOptions = {
  /** Types declared in other generated files; a reference to one becomes an import. */
  externalTypes?: ExternalTypes;
};

export type RenderedSurface = {
  /** The declaration file contents, or `null` when the surface exports nothing. */
  source: string | null;
  warnings: RenderWarning[];
};

type ContextFactory = (file: string, location: string) => RenderContext;

/** The first line of every generated file; identifies files this tool owns. */
export const GENERATED_HEADER_LINE = '// @generated by @expo/modules-cli. Do not edit by hand.';

const HEADER = `${GENERATED_HEADER_LINE}\n// Regenerate with \`expo-modules generate-types\`.\n`;

/**
 * Swift types provided by `expo-modules-core` that the scanner reports as plain references, with the
 * TypeScript type each converts to and from. A type with `from` is imported from that module; the
 * others are TypeScript globals.
 */
const CORE_TYPES: Record<string, { name: string; from?: string }> = {
  TypedArray: { name: 'TypedArray', from: 'expo-modules-core' },
  ArrayBuffer: { name: 'ArrayBuffer' },
};

/** The base class of every native module instance on the JS side. */
const NATIVE_MODULE_BASE = { name: 'NativeModule', from: 'expo-modules-core' };

/**
 * Renders a scanned surface as one TypeScript declaration file: records first, then shared
 * objects, then modules, so every declaration precedes the ones that reference it. References to
 * types declared elsewhere (other generated files, `expo-modules-core`) become type-only imports.
 */
export function renderSurface(
  surface: ExportedSurface,
  { externalTypes = {} }: RenderOptions = {}
): RenderedSurface {
  const warnings: RenderWarning[] = [];

  // A declaration whose TS name is not an identifier cannot be emitted; it is reported and left out,
  // so references to it resolve as unknown rather than to an invalid declaration.
  const declarable = <T extends { name: string; file: string }>(
    items: T[],
    tsName: (item: T) => string
  ) =>
    items.filter((item) => {
      if (isIdentifier(tsName(item))) {
        return true;
      }
      warnings.push({
        file: item.file,
        location: item.name,
        message: `'${tsName(item)}' is not a valid TypeScript identifier, so its declaration was skipped`,
      });
      return false;
    });
  const records = declarable(surface.records, (record) => record.name);
  const sharedObjects = declarable(surface.sharedObjects, (sharedObject) => sharedObject.jsName);
  const modules = declarable(surface.modules, (module) => module.jsName);

  // Swift type name -> the TS name it is declared under in this file.
  const refs = new Map<string, string>();
  for (const record of records) {
    refs.set(record.name, record.name);
  }
  for (const sharedObject of sharedObjects) {
    refs.set(sharedObject.name, sharedObject.jsName);
  }
  for (const module of modules) {
    refs.set(module.name, module.jsName);
  }

  // Module specifier -> type names to import from it.
  const imports = new Map<string, Set<string>>();
  const addImport = ({ name, from }: { name: string; from: string }) => {
    const names = imports.get(from) ?? new Set<string>();
    names.add(name);
    imports.set(from, names);
  };
  const resolveRef = (name: string): string | undefined => {
    const local = refs.get(name);
    if (local) {
      return local;
    }
    const external = externalTypes[name];
    if (external) {
      addImport(external);
      return external.name;
    }
    const coreType = CORE_TYPES[name];
    if (coreType?.from) {
      addImport({ name: coreType.name, from: coreType.from });
    }
    return coreType?.name;
  };
  if (modules.length > 0) {
    addImport(NATIVE_MODULE_BASE);
  }

  const makeContext: ContextFactory = (file, location) => ({
    resolveRef,
    warn: (message) => {
      warnings.push({ file, location, message });
    },
  });

  const declarations = [
    ...records.map((record) => renderRecord(record, makeContext)),
    ...sharedObjects.map((sharedObject) => renderSharedObject(sharedObject, makeContext)),
    ...modules.map((module) => renderModule(module, makeContext)),
  ];
  if (declarations.length === 0) {
    return { source: null, warnings };
  }
  const importBlock = [...imports.entries()]
    .map(([from, names]) => `import type { ${[...names].sort().join(', ')} } from '${from}';\n`)
    .join('');
  const sections = importBlock ? [HEADER, importBlock, ...declarations] : [HEADER, ...declarations];
  return { source: sections.join('\n'), warnings };
}

function renderRecord(record: ExportedRecord, makeContext: ContextFactory): string {
  const members = record.properties.map((property) => {
    const type = renderType(
      property.type,
      makeContext(record.file, `${record.name}.${property.name}`)
    );
    return `${memberName(property.name)}${property.required ? '' : '?'}: ${type};`;
  });
  return block(`export type ${record.name} = {`, members, '};');
}

function renderSharedObject(
  sharedObject: ExportedSharedObject,
  makeContext: ContextFactory
): string {
  const members: string[] = [];
  if (sharedObject.constructorParameters) {
    const parameters = renderParameters(
      sharedObject.constructorParameters,
      sharedObject.file,
      `${sharedObject.name}.init`,
      makeContext
    );
    members.push(`constructor(${parameters});`);
  }
  for (const property of sharedObject.properties) {
    members.push(renderProperty(property, sharedObject, makeContext, { includeStatic: true }));
  }
  for (const fn of sharedObject.functions) {
    members.push(renderFunction(fn, sharedObject, makeContext, { includeStatic: true }));
  }
  return block(`export declare class ${sharedObject.jsName} {`, members, '}');
}

function renderModule(module: ExportedModule, makeContext: ContextFactory): string {
  // JS only ever sees the module instance that `requireNativeModule` returns, so a member the Swift
  // side declares `static` is still an instance member of that class in TS.
  const members = [
    ...module.properties.map((property) =>
      renderProperty(property, module, makeContext, { includeStatic: false })
    ),
    ...module.functions.map((fn) =>
      renderFunction(fn, module, makeContext, { includeStatic: false })
    ),
  ];
  return block(
    `export declare class ${module.jsName} extends ${NATIVE_MODULE_BASE.name} {`,
    members,
    '}'
  );
}

type Owner = { name: string; file: string };
type MemberOptions = { includeStatic: boolean };

function renderProperty(
  property: ExportedProperty,
  owner: Owner,
  makeContext: ContextFactory,
  { includeStatic }: MemberOptions
): string {
  const ctx = makeContext(owner.file, `${owner.name}.${property.name}`);
  let type: string;
  if (property.type) {
    type = renderType(property.type, ctx);
  } else {
    ctx.warn('type could not be determined from the declaration, rendered as unknown');
    type = 'unknown';
  }
  const modifiers = `${includeStatic && property.static ? 'static ' : ''}${property.readonly ? 'readonly ' : ''}`;
  return `${modifiers}${memberName(property.jsName)}: ${type};`;
}

function renderFunction(
  fn: ExportedFunction,
  owner: Owner,
  makeContext: ContextFactory,
  { includeStatic }: MemberOptions
): string {
  const location = `${owner.name}.${fn.name}`;
  const parameters = renderParameters(fn.parameters, owner.file, location, makeContext);
  const returns = renderReturnType(fn.returns, fn.async, makeContext(owner.file, `${location}()`));
  return `${includeStatic && fn.static ? 'static ' : ''}${memberName(fn.jsName)}(${parameters}): ${returns};`;
}

function renderParameters(
  parameters: ExportedParameter[],
  file: string,
  location: string,
  makeContext: ContextFactory
): string {
  const lastRequiredIndex = parameters.findLastIndex((parameter) => !parameter.optional);
  return parameters
    .map((parameter, index) => {
      const name = parameterName(parameter.name, index);
      const type = renderType(parameter.type, makeContext(file, `${location}(${name})`));
      if (!parameter.optional) {
        return `${name}: ${type}`;
      }
      // TypeScript only allows optional parameters at the end of the list. Swift allows a defaulted
      // parameter before a required one, so such a parameter accepts `undefined` explicitly instead.
      return index < lastRequiredIndex ? `${name}: ${type} | undefined` : `${name}?: ${type}`;
    })
    .join(', ');
}

/** Lays out a declaration body with two-space indentation and a trailing newline. */
function block(open: string, members: string[], close: string): string {
  if (members.length === 0) {
    return `${open}${close}\n`;
  }
  return `${open}\n${members.map((member) => `  ${member}`).join('\n')}\n${close}\n`;
}
